"""
ComfyUI Gemini Image Edit Plugin
支持使用Gemini API进行1-3张图片的编辑和生成
"""

from .gemini_image_edit_node import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_V1, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_V1
from .gemini_image_edit_v2_node import NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_V2, NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_V2

# 合并两个版本的节点映射
NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS_V1, **NODE_CLASS_MAPPINGS_V2}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS_V1, **NODE_DISPLAY_NAME_MAPPINGS_V2}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']